---
title: "Predicting the burned area of a forest fire in northeastern Portugal"
author: "Axel Sjöberg & John Rapp Farnes"
date: "14 maj 2019"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: 3
  pdf_document:
    fig_caption: yes
    number_sections: yes
    toc: yes
    toc_depth: 3
classoption: a4paper
---

```{r setup_knitr, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  collapse = TRUE,
  comment = "#>"
)

options(tinytex.verbose = TRUE)
```

```{r setup_pdf, eval = FALSE}
# Install from CRAN
install.packages('rmarkdown')
# Render PDF
install.packages("tinytex")
tinytex::install_tinytex()  # install TinyTeX

```

```{r, code = readLines("script.R")}

```


<!-- Abstract? -->

# Introduction

The aim of this paper is to use meteorological and other data collected in the northeast of Portugal to predict the burned area of a forest fire. The dependent variable in this paper will be the burned area of the forest (in ha) and the independent variables considered are listed below

# Analysis

```{r}
hist(dataset$area)
hist(dataset$rain)

hist(log(dataset$area))
hist(log(dataset$area + 1))
hist(log(dataset$rain))
hist(log(dataset$rain + 1))

hist(dataset$temp)
hist(dataset$RH)
hist(dataset$wind)

plot(dataset$X, dataset$Y)

#temp, RH, wind and rain
pairs(~ area + temp + RH + wind + rain, data = dataset)

pairs(~ log(area + 1) + temp + RH + wind + log(rain + 1), data = dataset)

```

```{r}
hist(dataset$FFMC)
hist((dataset$FFMC)^(1/3))


# FFMC, DMC, DC, ISI
pairs(~ area + FFMC + DMC + DC + ISI, data = dataset)
pairs(~ log(area + 1) + FFMC + DMC + DC + ISI, data = dataset)

pairs(~ FFMC + DMC + DC + ISI + temp + RH + wind + log(rain + 1), data = dataset)

# pairs(~ log(area + 1) + FFMC.squared + DMC + DC + ISI, data = dataset)
```


```{r}
dataset <- cbind(dataset, log.area = log(dataset$area + 1), log.rain = log(dataset$rain + 1))

```

```{r}
dataset.cut <- dataset[dataset$area > 0,]
dataset.cut

pairs(~ log(area) + temp + RH + wind, data = dataset.cut)


```



```{r}
inverse.log <- function(x) exp(x) - 1

model.wind <- plot.correlation.model(area ~ wind, "wind", c(0, 10))
model.temp <- plot.correlation.model(area ~ temp, "temp", c(0, 35))
model.RH <- plot.correlation.model(area ~ RH, "RH", c(15, 110))

summary(model.wind)
summary(model.temp)
summary(model.RH)

calc.metrics.models(list(model.wind, model.temp, model.RH), c("wind", "temp", "RH"))

```
```{r}
dataset
hist(dataset$area)
summary(dataset$area)
```

```{r}

dataset <- cbind(dataset, big.fire = ifelse(dataset$area > 0, 1, 0))

pairs(~ big.fire + temp + RH + wind, data = dataset)

```

```{r}

model.wind <- plot.binary.model(big.fire ~ wind, dataset$big.fire, dataset$wind, "wind", c(0, 10), 10)
model.temp <- plot.binary.model(big.fire ~ temp, dataset$big.fire, dataset$temp, "temp", c(0, 35), 10)
model.RH <- plot.binary.model(big.fire ~ RH, dataset$big.fire, dataset$RH, "RH", c(15, 110), 10)

summary(model.temp)
```

```{r}

model <- lm(log.area ~ wind + temp + RH, data = dataset)
sum <- summary(model)

sum
sum$adj.r.squared

model <- lm(log.area ~ wind * temp, data = dataset)
sum <- summary(model)

sum
sum$adj.r.squared

```



<!-- Citation: -->
<!--   P. Cortez and A. Morais. A Data Mining Approach to Predict Forest Fires using Meteorological Data.  -->
<!--   In J. Neves, M. F. Santos and J. Machado Eds., New Trends in Artificial Intelligence,  -->
<!--   Proceedings of the 13th EPIA 2007 - Portuguese Conference on Artificial Intelligence, December,  -->
<!--   Guimaraes, Portugal, pp. 512-523, 2007. APPIA, ISBN-13 978-989-95618-0-9.  -->
<!--   Available at: http://www.dsi.uminho.pt/~pcortez/fires.pdf -->

 <!-- http://www.dsi.uminho.pt/~pcortez/fires.pdf -->
 <!-- In the above reference, the output "area" was first transformed with a ln(x+1) function. -->
 <!-- Then, several Data Mining methods were applied. After fitting the models, the outputs were -->
 <!-- post-processed with the inverse of the ln(x+1) transform. Four different input setups were -->
 <!-- used. The experiments were conducted using a 10-fold (cross-validation) x 30 runs. Two -->
 <!-- regression metrics were measured: MAD and RMSE. A Gaussian support vector machine (SVM) fed -->
 <!-- with only 4 direct weather conditions (temp, RH, wind and rain) obtained the best MAD value: -->
 <!-- 12.71 +- 0.01 (mean and confidence interval within 95% using a t-student distribution). The -->
 <!-- best RMSE was attained by the naive mean predictor. An analysis to the regression error curve -->
 <!-- (REC) shows that the SVM model predicts more examples within a lower admitted error. In effect, -->
 <!-- the SVM model predicts better small fires, which are the majority.  -->
 

<!-- This is a very difficult regression task. It can be used to test regression methods. Also, -->
<!-- it could be used to test outlier detection methods, since it is not clear how many outliers -->
<!-- are there. Yet, the number of examples of fires with a large burned area is very small. -->


<!-- Attribute information: -->
<!--    1. X - x-axis spatial coordinate within the Montesinho park map: 1 to 9 -->
<!--    2. Y - y-axis spatial coordinate within the Montesinho park map: 2 to 9 -->
<!--    3. month - month of the year: "jan" to "dec"  -->
<!--    4. day - day of the week: "mon" to "sun" -->
<!--    5. FFMC - FFMC index from the FWI system: 18.7 to 96.20 -->
<!--    6. DMC - DMC index from the FWI system: 1.1 to 291.3  -->
<!--    7. DC - DC index from the FWI system: 7.9 to 860.6  -->
<!--    8. ISI - ISI index from the FWI system: 0.0 to 56.10 -->
<!--    9. temp - temperature in Celsius degrees: 2.2 to 33.30 -->
<!--    10. RH - relative humidity in %: 15.0 to 100 -->
<!--    11. wind - wind speed in km/h: 0.40 to 9.40  -->
<!--    12. rain - outside rain in mm/m2 : 0.0 to 6.4  -->
<!--    13. area - the burned area of the forest (in ha): 0.00 to 1090.84  -->
<!--    (this output variable is very skewed towards 0.0, thus it may make -->
<!--     sense to model with the logarithm transform).  -->

<!-- \newpage -->

