---
title: "Predicting the burned area of a forest fire in northeastern Portugal"
author: "Axel Sjöberg & John Rapp Farnes"
date: "14 maj 2019"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: 3
  pdf_document:
    fig_caption: yes
    number_sections: yes
    toc: yes
    toc_depth: 3
classoption: a4paper
---

```{r setup_knitr, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  collapse = TRUE,
  comment = "#>"
)

options(tinytex.verbose = TRUE)
```

```{r setup_pdf, eval = FALSE}
# Install from CRAN
install.packages('rmarkdown')
# Render PDF
install.packages("tinytex")
tinytex::install_tinytex()  # install TinyTeX

```

```{r, code = readLines("lib.R")}

```

```{r, code = readLines("script.R")}

```


```{r}
titanic <- read.csv("titanic.csv")
titanic <- subset(titanic, select = -c(Name))
colnames(titanic) <- c(
  "survived",
  "pclass",
  "sex",
  "age",
  "siblings.spouses",
  "parents.children",
  "fare"
)

titanic
```



<!-- Abstract? -->

# Introduction

<!-- Syfte -->

# Analysis

```{r}
ggpairs(titanic)
```

```{r}
hist(titanic$fare)

high.fare.passengers <- which(titanic$fare > 200)

low.fare.passengers <- which(titanic$fare <= 0)

titanic[high.fare.passengers,]
titanic[low.fare.passengers,]

length(high.fare.passengers)
length(low.fare.passengers)
```

```{r}
hist(titanic$parents.children)
which(titanic$parents.children > 2)
```


```{r}
# titanic <- titanic[-high.fare.passengers,]
#   
# hist(log(titanic$Fare))

titanic$log.fare <- log(titanic$fare + 1)
hist(titanic$log.fare)
```



```{r}
model.log.fare <- plot.binary.model(survived ~ log.fare, titanic, titanic$survived, titanic$log.fare, "log.fare", c(0, 500), 1)
plot.binary.model(survived ~ siblings.spouses, titanic, titanic$survived, titanic$siblings.spouses, "siblings.spouses", c(0, 10), 40)
plot.binary.model(survived ~ parents.children, titanic, titanic$survived, titanic$parents.children, "parents.children", c(0, 10), 40)
plot.binary.model(survived ~ age, titanic, titanic$survived, titanic$age, "age", c(0, 80), 40)

summary(model.log.fare)
dataset <- titanic
pR2(model.log.fare)["r2CU"]
```

```{r}
hist(log(titanic[which(titanic$pclass == 1),]$fare + 1))
hist(log(titanic[which(titanic$pclass == 2),]$fare + 1))
hist(log(titanic[which(titanic$pclass == 3),]$fare + 1))
```

## Survived vs age


Age vs survived
```{r}
model.age <- plot.binary.model(survived ~ age, titanic, titanic$survived, titanic$age, "age", c(0, 80), 40)

summary(model.age)
dataset <- titanic
pR2(model.age)["r2CU"]
```
 
```{r}
# titanic$age.group <- cut(titanic$age, c(0, 12, 20, 35, 55, 100), labels = c("Child", "Adolescent", "Young adult", "Adult", "Senior"))
# titanic$age.group <- cut(titanic$age, seq(0, 80, 10))
titanic$age.group <- cut(titanic$age, c(0, 10, 20, 30, 55, 100), labels = c("Child", "Adolescent", "Young adult", "Adult", "Senior"))
#titanic$age.group <- cut(titanic$age, c(0, 10, 30, 55, 100), labels = c("Child", "Adolescent/Young adult", "Adult", "Senior"))
titanic$age.group <- relevel(titanic$age.group, ref = "Adult")

table(titanic$age.group)

# plot(log.fare ~ age, data = titanic)
(cross.age.survive <- table(titanic$age.group, titanic$survived))
# (cross.age.pclass <- table(titanic$age.group, titanic$pclass))
# 
(freq.table <- prop.table(cross.age.survive, 1))
plot(freq.table[,2])
axis(1, at=1:nrow(freq.table), rownames(freq.table))

# boxplot(survived ~ age.group, data = titanic)

model.age.group <- glm(survived ~ age.group, data = titanic, family = "binomial")

(sum <- summary(model.age.group))

cbind(sum$coefficients, confint(model.age.group))
cbind(exp(sum$coefficients), exp(confint(model.age.group)))

x0 <- data.frame(age.group = rownames(freq.table))
pred <- predict(model.age.group, x0, se.fit = TRUE, type = "response")

standard.error <- 1.96
ci.prob <- cbind("2.5 %" = pred$fit - standard.error * pred$se.fit, 
                "97.5 %" = pred$fit + standard.error * pred$se.fit)

# xb <- predict(model.age.group, x0, se.fit = TRUE)
# ci.xb <- data.frame(lwr = xb$fit - standard.error * xb$se.fit,
#                     upr = xb$fit + standard.error * xb$se.fit)
# 
# cbind(xb$fit, ci.xb)

cbind(x0, pred$fit * 100, ci.prob * 100)

model.age <- glm(survived ~ age, data = titanic, family = "binomial")
sum.age <- summary(model.age)

data.frame(
    model = c("age", "age.group"),
    #r2 = c(sum$adj.r.squared, sum.age$adj.r.squared),
    aic = c(AIC(model.age), AIC(model.age.group))
)


plot(log(fare + 1) ~ age, data = titanic)
plot(log(fare + 1) ~ age.group, data = titanic)

```

```{r}
model.1 <- glm(survived ~ log(fare + 1) + age, data = titanic, family = "binomial")
model.2 <- glm(survived ~ log(fare + 1) + age.group, data = titanic, family = "binomial")
model.3 <- glm(survived ~ log(fare + 1) * age.group, data = titanic, family = "binomial")

# summary(model.1)
# summary(model.2)
# summary(model.3)

compare.models <- calc.metrics.models(list(model.1, model.2, model.3), c("age","age group","interaction"))
compare.models
```



<!-- ```{r} -->
<!-- hist(dataset$area) -->
<!-- hist(dataset$rain) -->

<!-- hist(log(dataset$area)) -->
<!-- hist(log(dataset$area + 1)) -->
<!-- hist(log(dataset$rain)) -->
<!-- hist(log(dataset$rain + 1)) -->

<!-- hist(dataset$temp) -->
<!-- hist(dataset$RH) -->
<!-- hist(dataset$wind) -->

<!-- plot(dataset$X, dataset$Y) -->

<!-- #temp, RH, wind and rain -->
<!-- pairs(~ area + temp + RH + wind + rain, data = dataset) -->

<!-- pairs(~ log(area + 1) + temp + RH + wind + log(rain + 1), data = dataset) -->

<!-- ``` -->

<!-- ```{r} -->
<!-- hist(dataset$FFMC) -->
<!-- hist((dataset$FFMC)^(1/3)) -->


<!-- # FFMC, DMC, DC, ISI -->
<!-- pairs(~ area + FFMC + DMC + DC + ISI, data = dataset) -->
<!-- pairs(~ log(area + 1) + FFMC + DMC + DC + ISI, data = dataset) -->

<!-- pairs(~ FFMC + DMC + DC + ISI + temp + RH + wind + log(rain + 1), data = dataset) -->

<!-- # pairs(~ log(area + 1) + FFMC.squared + DMC + DC + ISI, data = dataset) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- dataset <- cbind(dataset, log.area = log(dataset$area + 1), log.rain = log(dataset$rain + 1)) -->

<!-- ``` -->

<!-- ```{r} -->
<!-- dataset.cut <- dataset[dataset$area > 0,] -->
<!-- dataset.cut -->

<!-- pairs(~ log(area) + temp + RH + wind, data = dataset.cut) -->


<!-- ``` -->



<!-- ```{r} -->
<!-- inverse.log <- function(x) exp(x) - 1 -->

<!-- model.wind <- plot.correlation.model(area ~ wind, "wind", c(0, 10)) -->
<!-- model.temp <- plot.correlation.model(area ~ temp, "temp", c(0, 35)) -->
<!-- model.RH <- plot.correlation.model(area ~ RH, "RH", c(15, 110)) -->

<!-- summary(model.wind) -->
<!-- summary(model.temp) -->
<!-- summary(model.RH) -->

<!-- calc.metrics.models(list(model.wind, model.temp, model.RH), c("wind", "temp", "RH")) -->

<!-- ``` -->
<!-- ```{r} -->
<!-- dataset -->
<!-- hist(dataset$area) -->
<!-- summary(dataset$area) -->
<!-- ``` -->

<!-- ```{r} -->

<!-- dataset <- cbind(dataset, big.fire = ifelse(dataset$area > 0, 1, 0)) -->

<!-- pairs(~ big.fire + temp + RH + wind, data = dataset) -->

<!-- ``` -->

<!-- ```{r} -->

<!-- model.wind <- plot.binary.model(big.fire ~ wind, dataset$big.fire, dataset$wind, "wind", c(0, 10), 10) -->
<!-- model.temp <- plot.binary.model(big.fire ~ temp, dataset$big.fire, dataset$temp, "temp", c(0, 35), 10) -->
<!-- model.RH <- plot.binary.model(big.fire ~ RH, dataset$big.fire, dataset$RH, "RH", c(15, 110), 10) -->

<!-- summary(model.temp) -->
<!-- ``` -->


